### ISSUE TITLE
Add exact_match_reads_col config in options.yaml

### ISSUE THREAD

**Issue by gwaybio** [broadinstitute/pooled-cp-profiling-template#19]
This will be a required argument after merging broadinstitute/pooled-cell-painting-profiling-recipe#65

It will belong in the `process-spots` heading. For example:

```yaml
  process-spots:
    perform: true
    force_overwrite: true
    image_cols:
      well: "Metadata_Well"
      site: "Metadata_Site"
      plate: "Metadata_Plate"
    barcode_cols:
      - Barcode_MatchedTo_Barcode
    gene_cols:
      - Barcode_MatchedTo_GeneCode
    location_cols:
      - Location_Center_X
      - Location_Center_Y
    spot_score_cols:
      - Barcode_MatchedTo_Score
    foci_cols:
      - Barcode_BarcodeCalled
      - Barcode_MatchedTo_ID
    exact_match_reads_col: "exact_match_reads_per_cell"
```
